modLoader="javafml"
loaderVersion="[46,)" # Совместимо с Forge 46.x (для 1.20.1)
license="All rights reserved"

[[mods]]
modId="beyondus"
version="1.0.0"
displayName="Beyond Us"
description='''
Добавляет таинственного Херобрина, который следит за игроком и пугает.
'''

[[dependencies.beyondus]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
    
